// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzM4b6eYaHqKYtYWpur-A-WwOo-BjN8Ug',
    appId: '1:212841961575:web:7f646fa65b2d4f710c9cc2',
    messagingSenderId: '212841961575',
    projectId: 'mehdi1-fe454',
    authDomain: 'mehdi1-fe454.firebaseapp.com',
    storageBucket: 'mehdi1-fe454.appspot.com',
    measurementId: 'G-FH2PTNHP74',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBOBdKVZWeHBQoxxrF0jB_ZQo4tlzSlKE',
    appId: '1:212841961575:android:a0d479c663ca596b0c9cc2',
    messagingSenderId: '212841961575',
    projectId: 'mehdi1-fe454',
    storageBucket: 'mehdi1-fe454.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9LByp-IuQE_9FZh_jebcm7FUSEBKpyUI',
    appId: '1:212841961575:ios:194a7c5c4f76ef390c9cc2',
    messagingSenderId: '212841961575',
    projectId: 'mehdi1-fe454',
    storageBucket: 'mehdi1-fe454.appspot.com',
    iosBundleId: 'com.example.ffastpro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9LByp-IuQE_9FZh_jebcm7FUSEBKpyUI',
    appId: '1:212841961575:ios:399b0d1b889c1d0f0c9cc2',
    messagingSenderId: '212841961575',
    projectId: 'mehdi1-fe454',
    storageBucket: 'mehdi1-fe454.appspot.com',
    iosBundleId: 'com.example.ffastpro.RunnerTests',
  );
}
