// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAycD_WN1fxbvVfHpO8ptHx8jbrks88xog',
    appId: '1:929162421351:web:98093ec591cb1590d820c2',
    messagingSenderId: '929162421351',
    projectId: 'asadproject-f2871',
    authDomain: 'asadproject-f2871.firebaseapp.com',
    storageBucket: 'asadproject-f2871.appspot.com',
    measurementId: 'G-GSHHMM7TSV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD59ouyzzEqLdO7ioM4A7qcaDg7jr2feZs',
    appId: '1:929162421351:android:eecf8e7482572453d820c2',
    messagingSenderId: '929162421351',
    projectId: 'asadproject-f2871',
    storageBucket: 'asadproject-f2871.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2K1ZRS28mh2jjbRR2ebBJnI438o-agJs',
    appId: '1:929162421351:ios:e9d16fbfb84fca1fd820c2',
    messagingSenderId: '929162421351',
    projectId: 'asadproject-f2871',
    storageBucket: 'asadproject-f2871.appspot.com',
    iosBundleId: 'com.example.ffastpro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2K1ZRS28mh2jjbRR2ebBJnI438o-agJs',
    appId: '1:929162421351:ios:840d00550cfc837bd820c2',
    messagingSenderId: '929162421351',
    projectId: 'asadproject-f2871',
    storageBucket: 'asadproject-f2871.appspot.com',
    iosBundleId: 'com.example.ffastpro.RunnerTests',
  );
}
